spring:
  application:
    name: gateway-web
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      #唯一标识符
      - id: js-goods-route
        #用户需要路由到的服务地址
        uri: lb://goods
        #路由断言
        predicates:
        - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
        filters:
        #- PrefixPath=/brand
        - StripPrefix=1
        - name: RequestRateLimiter #请求数限流 名字不能随便写
          args:
           key-resolver: "#{@ipKeyResolver}"
           redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
           redis-rate-limiter.burstCapacity: 1 #令牌桶总容量
      #用户微服务
      - id: js-user-route
        uri: lb://user
        predicates:
        - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**,/api/menu/**
        filters:
        - StripPrefix=1
      #认证微服务
      - id: js-oauth-route
        uri: lb://user-auth
        predicates:
        - Path=/api/oauth/**
        filters:
        - StripPrefix=1
      #订单微服务
      - id: js-order-route
        uri: lb://order
        predicates:
        - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
        filters:
        - StripPrefix=1
      #购物车订单渲染微服务
      - id: js-order-web-route
        uri: lb://order-web
        #,/api/wxpay/**
        predicates:
        - Path=/api/wcart/**,/api/worder/**
        filters:
        - StripPrefix=1
      #秒杀微服务
      - id: js-seckill-route
        uri: lb://seckill
        predicates:
        - Path=/api/seckillGoods/**,/api/seckillOrder/**
        filters:
        - StripPrefix=1
      #秒杀渲染微服务
      - id: js-seckill-web-route
        uri: lb://seckill-web
        predicates:
        - Path=/api/wseckillgoods/**,/api/wseckillorder/**
        filters:
        - StripPrefix=1
      #商业微服务
      - id: js-business-route
        uri: lb://business
        predicates:
        - Path=/api/activity/**,/api/ad/**
        filters:
        - StripPrefix=1
      #支付微服务
      - id: js-pay-route
        uri: lb://pay
        predicates:
        - Path=/api/wxpay/**
        filters:
        - StripPrefix=1
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
# 暴露监控端点
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true